export const TABS_KEY = Symbol('tabs')
export const TABS_GROUP_KEY = Symbol('tabs_group')
export const TAB_KEY = Symbol('tab')
export const CONTROL_LEFT_KEY = Symbol('control_left')
export const CONTROL_RIGHT_KEY = Symbol('control_right')
export const CONTROL_SET_KEY = Symbol('control_set')
